### ISSUE TITLE
Retrieving image: Unpack freezes at 100%

### ISSUE THREAD

**Issue by tomponline** [canonical/lxd#10189]
@stgraber I have experienced what you mentioned with image unpack freezing on `Cmd.Wait()` even though the unpack process has gone.

Kernel: 5.4.0-107-generic
OS: Ubuntu Focal
Go: 1.18
Storage pool driver: dir
Instance type: VM

Command being run:
```
lxc init images:ubuntu/20.04/cloud v1 --vm -s vmpool5321
Creating v1
Retrieving image: Unpack: 100% (2.21GB/s)
```

pprof shoes this go routine waiting in the Go stdlib's `os/exec.(*Cmd).Wait` function:
```
goroutine 91664 [chan receive, 7 minutes]:
os/exec.(*Cmd).Wait(0xc0011889a0)
	/snap/go/9415/src/os/exec/exec.go:515 +0x188
os/exec.(*Cmd).Run(0x1845584?)
	/snap/go/9415/src/os/exec/exec.go:341 +0x39
github.com/lxc/lxd/shared.RunCommandSplit({0x0?, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1845584, 0x8}, {0xc0004401f8, 0x8, ...})
	/build/lxd/parts/lxd/src/shared/util.go:895 +0x1b3
github.com/lxc/lxd/shared.RunCommand(...)
	/build/lxd/parts/lxd/src/shared/util.go:912
github.com/lxc/lxd/lxd/storage.ImageUnpack.func1({{0xc001486be8, 0x2}, {0xc00056a406, 0xa}, 0xc0014fe9f0, {0x185fadb, 0x10}, {0x1838e00, 0x5}, 0xc0014fe990, ...}, ...)
	/build/lxd/parts/lxd/src/lxd/storage/utils.go:468 +0xc89
github.com/lxc/lxd/lxd/storage.ImageUnpack({0xc0011829c0, 0x60}, {{0xc001486be8, 0x2}, {0xc00056a406, 0xa}, 0xc0014fe9f0, {0x185fadb, 0x10}, {0x1838e00, ...}, ...}, ...)
	/build/lxd/parts/lxd/src/lxd/storage/utils.go:486 +0x87e
github.com/lxc/lxd/lxd/storage.(*lxdBackend).imageFiller.func1({{0xc001486be8, 0x2}, {0xc00056a406, 0xa}, 0xc0014fe9f0, {0x185fadb, 0x10}, {0x1838e00, 0x5}, 0xc0014fe990, ...}, ...)
	/build/lxd/parts/lxd/src/lxd/storage/backend_lxd.go:1543 +0x271
github.com/lxc/lxd/lxd/storage/drivers.(*common).runFiller(0x0?, {{0xc001486be8, 0x2}, {0xc00056a406, 0xa}, 0xc0014fe9f0, {0x185fadb, 0x10}, {0x1838e00, 0x5}, ...}, ...)
	/build/lxd/parts/lxd/src/lxd/storage/drivers/driver_common.go:256 +0x331
github.com/lxc/lxd/lxd/storage/drivers.(*dir).CreateVolume(0xc000cb8be0, {{0xc001486be8, 0x2}, {0xc00056a406, 0xa}, 0xc0014fe9f0, {0x185fadb, 0x10}, {0x1838e00, 0x5}, ...}, ...)
	/build/lxd/parts/lxd/src/lxd/storage/drivers/driver_dir_volumes.go:58 +0x44d
github.com/lxc/lxd/lxd/storage.(*lxdBackend).CreateInstanceFromImage(0xc000a6fec0, {0x1b65718, 0xc000d14000}, {0xc0003357c0, 0x40}, 0x0?)
	/build/lxd/parts/lxd/src/lxd/storage/backend_lxd.go:1594 +0x923
main.instanceCreateFromImage(_, _, {0x0, {0x0, 0x0}, 0x1, 0x0, {0x183fa4e, 0x7}, {0xc0003357c0, ...}, ...}, ...)
	/build/lxd/parts/lxd/src/lxd/instance.go:167 +0xc55
main.createFromImage.func1(0xc0007f5320?)
	/build/lxd/parts/lxd/src/lxd/instances_post.go:131 +0x7d3
github.com/lxc/lxd/lxd/operations.(*Operation).Run.func1(0xc0007f5320, 0xc0008f5880?)
	/build/lxd/parts/lxd/src/lxd/operations/operations.go:280 +0x42
created by github.com/lxc/lxd/lxd/operations.(*Operation).Run
	/build/lxd/parts/lxd/src/lxd/operations/operations.go:279 +0x118
```

and also apparently related (has same run time and is to do with exec):

```
goroutine 92818 [IO wait, 7 minutes]:
internal/poll.runtime_pollWait(0x7fe9882f5778, 0x72)
	/snap/go/9415/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000973680?, 0xc000d90600?, 0x1)
	/snap/go/9415/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/snap/go/9415/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc000973680, {0xc000d90600, 0x200, 0x200})
	/snap/go/9415/src/internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	/snap/go/9415/src/os/file_posix.go:31
os.(*File).Read(0xc000010850, {0xc000d90600?, 0x17841c0?, 0xc00060e6a0?})
	/snap/go/9415/src/os/file.go:119 +0x5e
bytes.(*Buffer).ReadFrom(0xc00047da40, {0x1b450e0, 0xc000010850})
	/snap/go/9415/src/bytes/buffer.go:204 +0x98
io.copyBuffer({0x1b401a0, 0xc00047da40}, {0x1b450e0, 0xc000010850}, {0x0, 0x0, 0x0})
	/snap/go/9415/src/io/io.go:412 +0x14b
io.Copy(...)
	/snap/go/9415/src/io/io.go:385
os/exec.(*Cmd).writerDescriptor.func1()
	/snap/go/9415/src/os/exec/exec.go:311 +0x3a
os/exec.(*Cmd).Start.func1(0xc00062d550?)
	/snap/go/9415/src/os/exec/exec.go:441 +0x25
created by os/exec.(*Cmd).Start
	/snap/go/9415/src/os/exec/exec.go:440 +0x715
```

From looking at what `ImageUnpack` does on line 468, its running `qemu-img dd`.

**Comment by tomponline** [comment]
We only started seeing this when switching to Go 1.18 so suspect a Go bug.

**Comment by stgraber** [comment]
The issue has disappeared after I moved the disk hotplug test to the last thing we run in this particular CI test.
So this suggests that the disk hotplug test is somehow triggering something weird inside of LXD or the kernel.

**Comment by tomponline** [comment]
@stgraber I've got a minimal reproducer of sorts that runs on standalone LXD on Go 1.18 and Jammy kernel.

```
#!/bin/bash
set -ex

waitVMAgent() (
 echo "waiting for vm agent"
  set +x
  local vmName=$1
  for i in $(seq 90) # Wait up to 90s.
  do
    if lxc info "${vmName}" | grep -qF 127.0.0.1; then
      return 0 # Success.
    fi

    sleep 1
  done

  echo "VM ${vmName} agent not running after ${i}s"
  return 1 # Failed.
)

truncate -s 5m "/home/user/disk.img"
lxc launch images:ubuntu/20.04 v1 --vm -s default
waitVMAgent v1
lxc exec v1 -- whoami

# Hotplug disks
lxc config device add v1 block1 disk source="/home/user/disk.img" readonly=true
sleep 3
[ "$(lxc exec v1 -- cat /sys/block/sdb/ro)" -eq 1 ]
lxc config device set v1 block1 readonly=false
sleep 3
[ "$(lxc exec v1 -- cat /sys/block/sdb/ro)" -eq 0 ]

lxc delete -f v1
rm "/home/user/disk.img"

lxc init images:ubuntu/20.04 v1 --vm -s default
lxc start v1
waitVMAgent v1
lxc info v1
lxc delete -f v1
```

I've observed that quite often the `lxc exec v1 -- cat /sys/block/sdb/ro` or `lxc delete -f v1` commands will fail abruptly with errors like:

```
Error: websocket: close 1006 (abnormal closure): unexpected EOF
```

My gut feeling here is that the disk hotplug code is playing fast and loose with FDs being passed to QEMU and then these are being closed and reused by Go for other things, and QEMU is then interfering with them. I saw similar things when doing disk passing by FD before and had to be careful with the ordering.

**Comment by tomponline** [comment]
Yes this does appear to be the issue, got a fix for it, testing now.
