### ISSUE TITLE
LXD 5.17 breaks RBAC

### ISSUE THREAD

**Issue by stgraber** [canonical/lxd#12181]
I've gotten a snap auto-update on some of my remaining LXD systems, specifically those that still rely on RBAC.

Ever since the update to LXD 5.17, every single HTTP request triggers a panic:
```
INFO   [2023-08-25T15:55:17Z] http: panic serving [2602:fc62:c:1000:cacb:9eff:fead:7889]:48828: assignment to entry in nil map
goroutine 427503 [running]:
net/http.(*conn).serve.func1()
	/snap/go/10319/src/net/http/server.go:1868 +0xb9
panic({0x1a90c20?, 0x20c0c70?})
	/snap/go/10319/src/runtime/panic.go:920 +0x270
github.com/canonical/lxd/lxd/auth.(*rbac).syncPermissions(0xc0008a6900, {0xc000b9fea2, 0x15})
	/build/lxd/parts/lxd/src/lxd/auth/driver_rbac.go:472 +0x40c
github.com/canonical/lxd/lxd/auth.(*rbac).UserAccess(0xc0008a6900, {0xc000b9fea2, 0x15})
	/build/lxd/parts/lxd/src/lxd/auth/driver_rbac.go:350 +0x10f
main.(*Daemon).createCmd.func1.1({0x1d3bbcb, 0x6}, 0xc0004e0000, {0xc000b9fea2, 0x15}, 0xc00147d9d8, 0xc00147d880)
	/build/lxd/parts/lxd/src/lxd/daemon.go:548 +0x202
main.(*Daemon).createCmd.func1({0x20d2a80, 0xc000920d20}, 0xc00279f400)
	/build/lxd/parts/lxd/src/lxd/daemon.go:554 +0xdfc
net/http.HandlerFunc.ServeHTTP(0xc00279f300?, {0x20d2a80?, 0xc000920d20?}, 0x1d36892?)
	/snap/go/10319/src/net/http/server.go:2136 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000534c00, {0x20d2a80, 0xc000920d20}, 0xc00279f200)
	/build/lxd/parts/lxd/src/.go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1c5
main.(*lxdHttpServer).ServeHTTP(0xc000052120, {0x20d2a80, 0xc000920d20}, 0xc00279f200)
	/build/lxd/parts/lxd/src/lxd/api.go:369 +0xd0
net/http.serverHandler.ServeHTTP({0xc000ade7b0?}, {0x20d2a80?, 0xc000920d20?}, 0x6?)
	/snap/go/10319/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc001214cf0, {0x20d6640, 0xc000ade240})
	/snap/go/10319/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 27
	/snap/go/10319/src/net/http/server.go:3086 +0x5cb 
```

A quick look through the LXD 5.17 changes show some reshuffling around the `lxd/auth` package when it comes to RBAC, so looks like something was missed. I'm a bit surprised as to how the RBAC tests would still pass though as that particular codepath should have been exercised by the RBAC tests I wrote back in the days.

**Comment by stgraber** [comment]
Looking around, code was apparently changed so that we just get an empty `rbac{}` struct now rather than the pre-initialized one we used to have. Most of the struct intiialization then happens in `validateConfig` (odd that a config validation function would mutate the struct...) but both `resources` and `permissions` are left untouched, meaning that they will be `nil`.

For `permissions` this ends up being fatal as the next time a sync occurs, an attempt to access one of its members is made, triggering the panic. For `resources`, it's usually atomically replaced so the same concern for writes doesn't happen, but I didn't look at all accesses, it's quite possible that there could be a race where it's accessed prior to initialization, also causing a panic.

**Comment by stgraber** [comment]
I've confirmed that this has taken down both of my clusters that run `latest/candidate` with the 3 production clusters expected to similarly be brought down should this be allowed to move to `latest/stable`.
